language: java
sudo: required
jdk:
  - oraclejdk8
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
services:
  - docker
install:
  - mvn clean install -B -Dmaven.test.skip
script:
  - mvn test -B
