from ubuntu:12.04
# make sure the package repository is up to date
run echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
run apt-get update

# Install vnc, xvfb in order to create a 'fake' display and firefox
run apt-get install -y x11vnc xvfb x11-xserver-utils
run apt-get install -y vnc4server
run apt-get install -y fluxbox
run mkdir /root/.vnc
# Setup a password
#run echo "123456" | vncpasswd
run     x11vnc -storepasswd 123456 ~/.vnc/passwd
# Autostart firefox (might not be the best way to do it, but it does the trick)
#run xhost +
